##### task1

In [9]:
import numpy as np
farenheit_arr = np.array([13, 77, 100, 0, 32])
@np.vectorize
def convert_to_celcius(arr:np.array):
    return (arr-32)*(5/9)
     
celcius_arr = convert_to_celcius(farenheit_arr)
np.printoptions(suppress=True, precision=2)
print(celcius_arr)

[-10.56  25.    37.78 -17.78   0.  ]


##### task2

In [11]:
nums_arr = np.random.randint(1, 10, (4))
powers_arr = np.random.randint(1, 5, (4))
@np.vectorize
def find_power_of_num(arr1, arr2):
    return arr1**arr2

result_arr = find_power_of_num(nums_arr, powers_arr)
print(result_arr)

[512  16  49   8]


##### task3

In [12]:
coef = np.array([
    [4, 5, 6],
    [3, -1, 1],
    [2, 1, -2]
])
Y = np.array([7, 4, 5])
result_xyz = np.linalg.solve(coef, Y)
print(result_xyz)

[ 1.7   0.62 -0.49]


##### task4

In [13]:
coef = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])
Y = np.array([12, -5, 15])

result1 = np.linalg.inv(coef)@Y
result2 = np.linalg.solve(coef,Y)
print(result1)
print(result2)

[ 0.49 -0.23  2.22]
[ 0.49 -0.23  2.22]
