##### task1

In [ ]:
import numpy as np
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


##### task2

In [23]:
import numpy as np
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:")
print(matrix_3x3)


3x3 Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


##### task3

In [36]:
import numpy as np
identity_matrix = np.eye(3, dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


##### task4

In [44]:
import numpy as np
random_mtrx = np.random.randint(1, 100, (3, 3, 3))
print(random_mtrx)

[[[13 70 41]
  [80 49 53]
  [12 46  8]]

 [[20 92 73]
  [54 80 72]
  [42 36 77]]

 [[32 47 13]
  [66  9 50]
  [32 11 90]]]


##### task5

In [51]:
import numpy as np
array10x10 = np.random.randint(1, 10, (10,10))
print(f"Max value: {np.max(array10x10)}")
print(f"Min value: {np.min(array10x10)}")


Max value: 9
Min value: 1


##### task6

In [56]:
import numpy as np
rand_vect = np.random.randint(1,100, (30,))
print(rand_vect)
mean = rand_vect.sum()/len(rand_vect)
print(f"Mean: {round(mean, 2)}")

[70 98 45 81  8 33 59 41 31 74 50 43 47 26 22  1 84 26 22 83 76 70 77 34
 53 89 28 95 89 50]
Mean: 53.5


##### task7

In [57]:
import numpy as np
matrix_org = np.random.randint(1,10, (5, 5))
mtrx_min = matrix_org.min()
mtrx_max = matrix_org.max() 
norm_matrix = (matrix_org-mtrx_min)/(mtrx_max-mtrx_min)
print(norm_matrix)

[[0.5   0.125 0.25  0.875 0.125]
 [0.375 1.    0.875 0.625 0.125]
 [0.125 0.125 0.    0.125 0.5  ]
 [1.    0.    0.375 1.    0.375]
 [0.    0.375 0.375 0.    0.125]]


##### task8

In [ ]:
import numpy as np
matrix_5x3 = np.random.randint(1, 10, (5, 3))
matrix_3x2 = np.random.randint(1, 10, (3, 2))
result_matrix = matrix_5x3@matrix_3x2
print(result_matrix)

[[ 32  34]
 [ 52  46]
 [ 64  72]
 [ 98 116]
 [ 88 104]]


##### task9

In [62]:
import numpy as np
mtrx1 = np.random.randint(1, 10, (3,3))
mtrx2 = np.random.randint(1, 10, (3,3))
dot_prdct = np.dot(mtrx1, mtrx2)
print(dot_prdct.sum())


550


##### task10

In [63]:
import numpy as np
mtrx = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(mtrx.transpose())

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


##### task11

In [ ]:
import numpy as np
mtrx = np.random.randint(1,9, (3,3))
det_mtrx = np.linalg.det(mtrx)
print(f"Determinant: {det_mtrx}")